# Generated by Django 2.1 on 2018-08-21 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftDayModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField(choices=[(0, 'weekend'), (1, 'holiday'), (2, 'special')])),
                ('date', models.DateField()),
                ('show_datetime', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'День с дежурствами',
                'verbose_name_plural': 'Дни с дежурствами',
                'db_table': 'main_shiftday',
                'ordering': ['date', 'type'],
            },
        ),
        migrations.CreateModel(
            name='ShiftModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField(choices=[(0, 'normal'), (1, 'beeper'), (2, 'special')])),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ShiftDayModel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Дежурство',
                'verbose_name_plural': 'Дежурства',
                'db_table': 'main_shift',
            },
        ),
        migrations.RemoveField(
            model_name='slotmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='SlotModel',
        ),
        migrations.AlterUniqueTogether(
            name='shiftmodel',
            unique_together={('user', 'day')},
        ),
    ]
