# Generated by Django 2.1 on 2018-08-21 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180821_1008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftmodel',
            options={'ordering': ('day__date', 'user'), 'verbose_name': 'Дежурство', 'verbose_name_plural': 'Дежурства'},
        ),
    ]
